### ISSUE TITLE
List of places to donate

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **a list of places where I can bring my old stuff ** 
so that **I don't have to do the research myself** 
## Description (Text, Scribble, Wireframe, Design)
- This will be shown as a long list of cards
- Each Card shows the name of the place, the address and what kind of things can be brought there
## Acceptance criteria
- [ ] Cards have to be visually seperated
- [ ] Name and address need to be in simple text in a good readable size
- [ ] The kind of accepted things should be shown in tags
- [ ] Cards are scolled vertically
## Tasks
- [ ] Create a cards.json
- [ ] Create a home component where the cards will be rendered in (including first design)
- [ ] Create a card component (including first design)
- [ ] Create a tag component that can be rendered in the card (including first design)
- [ ] Testing
## Size
(small)
