### ISSUE TITLE
Bookmark places

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#11]
## Value statement - a requirement, not a solution
As a **user** 
I need **to be able to bookmark my favorite places** 
so that **I don't need to scroll through the whole list** 
## Description (Text, Scribble, Wireframe, Design)
- A bookmark icon (heart?) needs to be on the top (right) on each place
## Acceptance criteria
- [ ]  A click on the icon toggled the color and bookmarks(unbookmarks) the places in the local storage
## Tasks
- [ ] Create a bookmark component in storybook
- [ ] Add bookmark component to app
- [ ] Add the toggle logic to the bookmark
## Size
medium
