### ISSUE TITLE
Bookmark filter

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#12]
## Value statement
As a **user** 
I need **to find my bookmarked places easily** 
so that **it will be less effort to find them again** 
## Description (Text, Scribble, Wireframe, Design)
- A button/text on top of the page says [Lieblings "make it stay"-Orte] resp. [Alle "make it stay"-Orte]
## Acceptance criteria
- [ ]Text toggles on click
- [ ]Only bookmarked places resp. all places are shown
## Tasks
- [ ] Create bookmark filter component in storybook
- [ ] Add bookmark filter component to app
- [ ] Add toggle logic
- [ ] Add state  for bookmark filter 
- [ ] Testing

## Size
medium
