### ISSUE TITLE
Filter meta-infos

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **to filter the detailed information** 
so that **I will find the perfect place for my things** 
## Description (Text, Scribble, Wireframe, Design)
- The pop-up filter menu shows also the meta-infos
## Acceptance criteria
- [ ] meta-infos are addes to the filter menu shows the meta-infos
- [ ] after selecting the meta-infos only places that fulfil the filter are shown
## Tasks
- [ ] Apply the filter logic for the meta-infos
- [ ] Testing
## Size
small
