### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#16]
## Value statement 
As a **app-owner** 
I need **the users to know the name of the app**
so that **they will remember it** 
## Description (Text, Scribble, Wireframe, Design)
- The app has a header with the name "make it stay" on it
## Acceptance criteria
- [ ] Header stays on top
- [ ] Name "make it stay" is in the center of the header
- [ ] Body scrolls below the header

## Tasks
- [ ] Create header component in storybook
- [ ] Add header component to app
- [ ] Testing

## Size
small
