### ISSUE TITLE
Sort places by citites

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **to find the places in my city easier** 
so that **I don't have to look into the address details on each card** 
## Description (Text, Scribble, Wireframe, Design)
- The list of places is seperated by city-names
- Under each city-name only the places in one city are shown
## Acceptance criteria
- [ ] The city-names are visually highlighted/seperated from the cards
- [ ] Under each city-name only the places in one city are shown
## Tasks
- [ ] Create a component for the seperation
## Size
Small
