### ISSUE TITLE
Add Styling & Animation to Filter Menu

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#20]
## Value statement
As a **user** 
I need **want the filter menu to look nice** 
so that **I am happy looking at it** 
## Description (Text, Scribble, Wireframe, Design)
- The Pop-up of the Filter Menu is animated, slide-in
- The frame of the Filter Menu looks nice
- The checkboxes match the design of the app

## Acceptance criteria
- [ ] The Filter Menu slides-in
- [ ] Checkboxes have custom design
## Tasks
- [ ] Add Animation to Filter Menu
- [ ] Add Styling to Filter Menu
- [ ] Add Styling to checkboxes
## Size
 medium
