### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#21]
## Value statement
As a **user** 
I need **to search through the places** 
so that **I will find the best place to drop-off my things** 
## Description (Text, Scribble, Wireframe, Design)
- A search bar on top of the page searches through all the places
## Acceptance criteria
- [ ] A search bar is shown
- [ ] The user can type in any word
- [ ] While typing the places change (only places that include the typed letters are shown)
- [ ] If no place matches the criteria an error is shown "Kein make it stay-Ort entspricht deiner Suche"
- [ ] Enter/Submit shows the results and clears the search field
## Tasks
- [ ] Add search bar to storybook
- [ ] Add search bar to app
- [ ] Add filter logic on typed content to search bar and places
- [ ] Add error message
## Size
large
