### ISSUE TITLE
Add google maps

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#22]
## Value statement 
As a **user** 
I need **to see the location of the places on a map** 
so that **I will know where to go** 
## Description (Text, Scribble, Wireframe, Design)
- User can select to see the places as a list or on a map
- Each place can be opened in a map
## Acceptance criteria
- [ ] On top of the page there are two buttons: List/Map
- [ ] A click on Map opens a page that shows the places on a map
- [ ] A click on List switches back to the Homepage
- [ ] On each place there is a map-icon that changes to a screen and shows it on a map
## Tasks
- [ ] Install google maps
- [ ] Add geolocation to places
- [ ] Add Map component 
- [ ] Add two new Button components to home and map component
- [ ] Add map-icon
## Size
large
