### ISSUE TITLE
Toggle detailed description

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **to know the opening times of a place and a description** 
so that **I will go there at the right time and know what will happen to my things after I brought them there** 
## Description (Text, Scribble, Wireframe, Design)
- The card needs a button or link [show details] resp. [hide details]
## Acceptance criteria
- [ ] Details are hidden by default
- [ ] A click on the button shows ore hides the details (opening times, description, website)
- [ ] The text on the button changes on click
## Tasks
- [ ] Create a button component (including design)
- [ ] Add the details to the card component
- [ ] Add a toggle logic to button and card
- [ ] Testing

## Size
Medium
