### ISSUE TITLE
Toggle detailed description

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#4]
## Value statement
As a **user** 
I need **to only see the detailed description of the places I am interested in** 
so that **I can scroll the long list faster** 
## Description (Text, Scribble, Wireframe, Design)
- The card needs a button or link [show details] resp. [hide details]
## Acceptance criteria
- [ ] Details are hidden by default
- [ ] A click on the button shows ore hides the details (opening times, description, website)
- [ ] The text on the button changes on click
## Tasks
- [ ] Create a button component in storybook (including design)
- [ ] Add the button component to the App
- [ ] Add a toggle logic to button and place
- [ ] Testing

## Size
Medium
