### ISSUE TITLE
Filter catgories

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#8]
## Value statement
As a **user** 
I need **to filter the catgories** 
so that **I only see the places where I can drop-of the things I want to get rid of (e.g. clothing or books)** 
## Description (Text, Scribble, Wireframe, Design)
- On the top of the page there needs to be a filter button/text
- A click on the button opens a pop-up menu where the categories can be chosen
- After chosing one (or severeal) categories the list of places only shows places that accept the chosen categories
## Acceptance criteria
- [ ] A filter button is on top of the page
- [ ] A click on the button opens a filter menu
- [ ] After selecting the categories in the menu, the places are filtered by those categories
## Tasks
- [ ] Create filter button component in storybook 
- [ ] Add filter button component to app
- [ ] Create filter menu component in storybook 
- [ ] Add filter menu component to app
- [ ] Add filter logic

## Size
medium
