### ISSUE TITLE
Meta-Infos

### ISSUE THREAD

**Issue by maje02** [maje02/capstone-project#9]
## Value statement
As a **user** 
I need **to know how my stuff can get to the place and if I can donate or sell my things there** 
so that **I will choose the right place** 
## Description 
- Meta-Infos need to be added to the information of the places:
- Way of transport: bring it there, pick-up or postal
- Donation or selling of old things?
- The information should be visible on the place information, but not as highlighted as the rest of information
## Acceptance criteria
- [ ] Meta-infos are visible on each place
## Tasks
- [ ] Add the Meta-infos to places.json
- [ ] Add the Meta-infos to places.js
- [ ] Testing
## Size
small
